In [13]:
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
import datetime

In [2]:
from matplotlib import pyplot as plt

plt.rcParams['backend'] = 'TkAgg'
plt.rcParams["figure.figsize"] = [7.50, 3.50]
plt.rcParams["figure.autolayout"] = True

# Function to print mouse click event coordinates
def onclick(event):
   print([event.xdata, event.ydata])

# Create a figure and a set of subplots
fig, ax = plt.subplots()

# Plot a line in the range of 10
ax.plot(range(10))

# Bind the button_press_event with the onclick() method
fig.canvas.mpl_connect('button_press_event', onclick)

# Display the plot
plt.show()

In [3]:
#plt.rcParams['backend'] = 'TkAgg'
plt.rcParams["figure.figsize"] = [5, 5]
#plt.rcParams["figure.autolayout"] = True

x = []
# Function to print mouse click event coordinates
def onclick(event):
    global x
    valor = input('descreva')
    x.append((event.xdata, event.ydata, valor))

# Create a figure and a set of subplots
fig, ax = plt.subplots()


img = mpimg.imread('./imagens/coca-cola.jpg')
fig = plt.imshow(img).figure

# Bind the button_press_event with the onclick() method
fig.canvas.mpl_connect('button_press_event', onclick)

# Display the plot
plt.show()

In [4]:
## plt.rcParams['backend'] = 'TkAgg'
plt.rcParams["figure.figsize"] = [5, 5]
plt.rcParams["figure.autolayout"] = True

pontos = []
# Function to print mouse click event coordinates
def onclick(event):
    global pontos
    valor = input('descreva')
    pontos.append((event.xdata, event.ydata, valor))

# Create a figure and a set of subplots
fig, ax = plt.subplots()

ax.scatter([1,2,3,4,5],
        [1,4,9,16,25])

# Bind the button_press_event with the onclick() method
fig.canvas.mpl_connect('button_press_event', onclick)

# Display the plot
plt.show()

descreva 1
descreva 5
descreva 5
descreva 25
descreva 0
descreva 1
descreva 2
descreva 3
descreva 4


In [23]:
pontos

[(1.0140480823551568, -0.006099838167558325, '1'),
 (5.011085305379449, -0.006099838167558325, '5'),
 (0.8151905090703659, 5.022158595792357, '5'),
 (0.8151905090703659, 25.07603635005602, '25'),
 (0.9941623250266776, 0.9995518486244244, '0'),
 (1.9983930701148707, 4.075662890576373, '1'),
 (2.992680936538824, 8.98560936138429, '2'),
 (4.006854560291256, 16.20263911365617, '3'),
 (4.99119954805097, 25.07603635005602, '4')]

In [40]:
x_0 = pontos[0][0]
x_1 = pontos[1][0]
y_0 = pontos[2][1]
y_1 = pontos[3][1]
X_0 = np.float64(pontos[0][2])
X_1 = np.float64(pontos[1][2])
Y_0 = np.float64(pontos[2][2])
Y_1 = np.float64(pontos[3][2])

In [42]:
a_h = (X_1-X_0)/(x_1-x_0)

b_h = ((X_0 - a_h*x_0)+(X_1 - a_h*x_1) )/2

a_v = (Y_1-Y_0)/(y_1-y_0)

b_v = ((Y_0 - a_v*y_0)+(Y_1 - a_v*y_1) )/2

In [48]:
Pontos = np.array(pontos).astype('float')
Pontos

array([[ 1.01404808e+00, -6.09983817e-03,  1.00000000e+00],
       [ 5.01108531e+00, -6.09983817e-03,  5.00000000e+00],
       [ 8.15190509e-01,  5.02215860e+00,  5.00000000e+00],
       [ 8.15190509e-01,  2.50760364e+01,  2.50000000e+01],
       [ 9.94162325e-01,  9.99551849e-01,  0.00000000e+00],
       [ 1.99839307e+00,  4.07566289e+00,  1.00000000e+00],
       [ 2.99268094e+00,  8.98560936e+00,  2.00000000e+00],
       [ 4.00685456e+00,  1.62026391e+01,  3.00000000e+00],
       [ 4.99119955e+00,  2.50760364e+01,  4.00000000e+00]])

In [49]:
x = Pontos[4:, 0]
y = Pontos[4:, 1]
x, y

(array([0.99416233, 1.99839307, 2.99268094, 4.00685456, 4.99119955]),
 array([ 0.99955185,  4.07566289,  8.98560936, 16.20263911, 25.07603635]))

In [50]:
X = a_h*x+b_h
Y = a_v*y+b_v

In [47]:
type(b_h)

numpy.float64

In [51]:
X

array([0.9800995 , 1.98507463, 2.9800995 , 3.99502488, 4.9800995 ])

In [52]:
Y

array([ 0.98820059,  4.0560472 ,  8.95280236, 16.15044248, 25.        ])